'use client';
import React,{useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Check,ArrowRight,ArrowLeft,Sparkles,Upload,RefreshCw,Clock} from 'lucide-react';
import {AuthGuard} from '@/components/auth/AuthGuard';
import {GitHubIntegration} from '@/components/common/GitHubIntegration';
import {FirstDayBrief} from '@/components/common/FirstDayBrief';
import {useAuth} from '@/lib/auth/AuthContext';
import {api} from '@/lib/api/client';
import type {JourneyState,PersonalizedChallenge} from '@/lib/journey';
import type {CareerTrack} from '@/lib/types';
const steps=['Your starting point','Show what you know','Choose your direction','First-day challenge','Meet your team'];
const input='w-full rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-950 p-3 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/40';
const primary='inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-40';
export default function Page(){return <AuthGuard><Onboarding/></AuthGuard>;}
function Onboarding(){
 const {user,refreshProfile}=useAuth();
 const [state,setState]=useState<JourneyState>();const [tracks,setTracks]=useState<CareerTrack[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const [verified,setVerified]=useState(false);const [code,setCode]=useState('');const [message,setMessage]=useState('');const [saved,setSaved]=useState('');
 const [step,setStep]=useState(0);const [level,setLevel]=useState('BEGINNER');const [skills,setSkills]=useState<string[]>([]);const [skill,setSkill]=useState('');const [goal,setGoal]=useState('');const [hours,setHours]=useState(6);const [track,setTrack]=useState('');const [mode,setMode]=useState<'AUTOMATED'|'GUIDED'>('AUTOMATED');const [project,setProject]=useState('');const [note,setNote]=useState('');const [answers,setAnswers]=useState([-1,-1,-1]);const [solution,setSolution]=useState('');const [feedback,setFeedback]=useState('');
 const [challenge,setChallenge]=useState<PersonalizedChallenge>();const [challengeLoading,setChallengeLoading]=useState(false);
 const queue=useRef<Promise<unknown>>(Promise.resolve());const draftKey='devsim-first-day:'+user?.userId;
 const submitted=!!state&&['ASSIGNED','PENDING_REVIEW'].includes(state.journey.status);
 async function load(){setLoading(true);setError('');try{const [j,t,v]=await Promise.all([api.getJourney(),api.getCareerTracks(),api.getEmailVerification()]);setState(j.data);setTracks(t.data);setVerified(v.data.verified);const x=j.data.journey;setSkills(x.skills.split(',').map(s=>s.trim()).filter(Boolean));setGoal(x.goal);setHours(x.weeklyHours);setMode(x.assignmentMode);setTrack(user?.profile?.selectedCareerTrack?.id||t.data[0]?.id||'');setLevel(user?.profile?.experienceLevel||'BEGINNER');setProject(x.preferredProjectId||j.data.recommendations[0]?.project.id||'');setNote(x.requestNote||'');setSolution(x.assessmentAnswer||'');setStep(x.assessmentScore!=null||x.assessmentSkipped?4:0);
 if(['DRAFT','REJECTED'].includes(x.status))try{const d=JSON.parse(localStorage.getItem(draftKey)||'null');if(d){setStep(Math.min(4,Math.max(0,d.step||0)));setSkills(d.skills||[]);setGoal(d.goal||'');setHours(d.hours||6);setTrack(d.track||t.data[0]?.id||'');setLevel(d.level||'BEGINNER');setMode(d.mode||'AUTOMATED');setProject(d.project||x.preferredProjectId||j.data.recommendations[0]?.project.id||'');setNote(d.note||'');setAnswers(d.answers||[-1,-1,-1]);setSolution(d.solution||'');}}catch{}await refreshProfile();}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 function payload(){return {skills,goal,weeklyHours:hours,careerTrackId:track,experienceLevel:level,assignmentMode:mode,projectId:project||undefined,requestNote:note};}
 useEffect(()=>{if(loading||!state||submitted)return;try{localStorage.setItem(draftKey,JSON.stringify({step,skills,goal,hours,track,level,mode,project,note,answers,solution}));setSaved('Draft saved on this device');}catch{setSaved('Continue to save to your account');}if(busy||!skills.length||!goal.trim()||!track)return;const timer=setTimeout(()=>{queue.current=queue.current.catch(()=>{}).then(()=>api.saveJourney(payload())).then(r=>{setState((r as {data:JourneyState}).data);setSaved('Saved to your account');}).catch(()=>setSaved('Saved locally; Continue will retry account sync'));},900);return()=>clearTimeout(timer);},[loading,submitted,step,skills,goal,hours,track,level,mode,project,note,answers,solution,busy]);
 async function save(){await queue.current.catch(()=>{});const r=await api.saveJourney(payload());setState(r.data);return r.data;}
 async function act(action:()=>Promise<void>){setBusy(true);setError('');try{await action();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function add(value:string){const clean=value.trim();if(clean&&clean.length<=60&&skills.length<40&&!skills.some(s=>s.toLowerCase()===clean.toLowerCase()))setSkills([...skills,clean]);setSkill('');}
 async function loadChallenge(retry=false){setChallengeLoading(true);setError('');try{await save();const r=await api.getJourneyChallenge(retry);setChallenge(r.data);const previous=JSON.parse(localStorage.getItem(draftKey+':challenge')||'null');setAnswers(previous?.id===r.data.id?previous.answers:Array(r.data.questions.length).fill(-1));setSolution(previous?.id===r.data.id?previous.solution:'');}catch(e){setError((e as Error).message);}finally{setChallengeLoading(false);}}
 useEffect(()=>{if(step===3&&!loading&&verified&&!submitted)void loadChallenge();},[step,loading,verified]);
 useEffect(()=>{if(challenge)try{localStorage.setItem(draftKey+':challenge',JSON.stringify({id:challenge.id,answers,solution}));}catch{}},[challenge,answers,solution]);
 async function next(){if(step===1&&!skills.length)throw Error('Add one skill you know or are learning.');if(step===2){if(!goal.trim()||!track)throw Error('Choose your direction and a goal.');await save();}if(step===3){if(!challenge||answers.length!==challenge.questions.length||answers.some(a=>a<0)||!solution.trim())throw Error('Answer the questions and add a solution, or skip this optional challenge.');const r=await api.assessJourney(answers,solution,challenge!.id);setFeedback(r.data.feedback);const j=await api.getJourney();setState(j.data);setProject(j.data.recommendations[0]?.project.id||'');}setStep(step+1);}
 async function skip(){await save();const r=await api.skipAssessment();setState(r.data);setFeedback('Challenge skipped. Start conservatively; ticket reviews guide your next level.');setStep(4);}
 async function finish(){if(!verified)throw Error('Verify your email first.');await save();const r=await api.completeJourney(project);setState(r.data);localStorage.removeItem(draftKey);await refreshProfile();}
 if(loading)return <div className="p-20 text-center"><RefreshCw className="mx-auto motion-safe:animate-spin"/>Preparing your first day...</div>;
 if(!state)return <div className="p-12 text-center"><p role="alert">{error}</p><button className={primary} onClick={load}>Retry</button></div>;
 const selected=state.recommendations.find(r=>r.project.id===project);const trackName=tracks.find(t=>t.id===track)?.name||'your chosen stack';
 return <main className="mx-auto max-w-6xl px-5 py-10"><div className="mb-8 flex justify-between gap-3"><span className="inline-flex items-center gap-2 text-xs text-indigo-500"><Sparkles size={15}/>YOUR FIRST DAY AT DEVSIM</span><span className="text-xs text-slate-400">{submitted?'Welcome kit':verified?saved:'Account created / verify email'}</span></div><div className="grid lg:grid-cols-[260px_1fr] gap-10"><aside><h1 className="text-4xl font-bold tracking-tight">You belong<br/><span className="text-indigo-500">on a team.</span></h1><p className="mt-4 text-sm leading-6 text-slate-500">A personal starting point, a project that fits, and your first engineering task.</p><ol className="mt-8 space-y-5">{steps.map((s,i)=><li key={s} aria-current={i===step?'step':undefined} className={`flex gap-3 items-center text-sm ${i===step?'text-indigo-500 font-semibold':'text-slate-500'}`}><span className="w-8 h-8 rounded-full border border-indigo-300 dark:border-indigo-800 flex items-center justify-center">{i<step||submitted?<Check size={14}/>:i+1}</span>{s}</li>)}</ol><p className="mt-8 text-xs text-slate-500 leading-5">Resume is optional. Your draft is saved as you go. The challenge never rejects your registration.</p></aside><section className="rounded-3xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-6 md:p-9">{state.journey.status==='REJECTED'&&<p className="mb-5 p-4 rounded-xl bg-amber-50 dark:bg-amber-950/30 text-sm">Admin requested changes: {state.journey.adminNote}</p>}{error&&<p role="alert" className="mb-5 p-4 rounded-xl bg-red-50 dark:bg-red-950/40 text-red-500 text-sm">{error}</p>}
 {!verified?<div className="space-y-5 journey-enter"><h2 className="text-2xl font-bold">First, verify your email.</h2><p className="text-sm text-slate-500">Send a six-digit code to {user?.email} to secure your account.</p><button disabled={busy} className={primary} onClick={()=>act(async()=>{const r=await api.sendEmailVerification();setMessage(r.data.message);})}>Send verification code</button><label className="block text-sm">Verification code<input className={`${input} mt-2`} inputMode="numeric" autoComplete="one-time-code" value={code} maxLength={6} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/></label><button disabled={busy||code.length!==6} className={primary} onClick={()=>act(async()=>{await api.verifyEmail(code);setVerified(true);setMessage('');})}>Verify & start my first day</button>{message&&<p className="text-xs text-slate-500" role="status">{message}</p>}</div>:submitted?<div><div className="flex items-center gap-3 text-emerald-500">{state.journey.status==='ASSIGNED'?<Check/>:<Clock/>}<h2 className="text-xl font-bold">{state.journey.status==='ASSIGNED'?'Welcome to your team.':'Your request is with the admin.'}</h2></div><FirstDayBrief state={state} name={user?.profile?.name||'Developer'} employeeId={user?.userId||''}/>{state.journey.status==='ASSIGNED'?<Link href="/workspace" className={primary}>Start my first day <ArrowRight size={15}/></Link>:<p className="text-sm text-slate-500 mb-5">Your preferences are submitted. Project access opens after admin approval.</p>}<button className="ml-4 text-sm underline" onClick={load}>Refresh status</button></div>:<><div key={step} className="journey-enter"><p className="text-xs text-indigo-500 mb-2">STEP {step+1} OF 5</p><h2 className="text-2xl font-bold mb-6">{steps[step]}</h2>
 {step===0&&<div className="space-y-4">{[{value:'BEGINNER',title:'I am learning',text:'Build confidence with guided starter tickets.'},{value:'INTERMEDIATE',title:'I have built projects',text:'Turn your skills into reviewed engineering work.'},{value:'ADVANCED',title:'I have worked professionally',text:'Practice deeper architecture and delivery decisions.'}].map(o=><button key={o.value} aria-pressed={level===o.value} onClick={()=>setLevel(o.value)} className={`w-full rounded-2xl border p-5 text-left ${level===o.value?'border-indigo-500 bg-indigo-50 dark:bg-indigo-950/40':'border-slate-200 dark:border-slate-700'}`}><span className="font-semibold">{o.title}</span><p className="mt-2 text-sm text-slate-500">{o.text}</p></button>)}</div>}
 {step===1&&<div className="space-y-5"><label className="block border-2 border-dashed border-indigo-300 dark:border-indigo-800 rounded-2xl p-7 text-center cursor-pointer"><Upload className="mx-auto text-indigo-500 mb-3"/><span>{state.journey.resumeName||'Upload a resume (optional)'}</span><p className="text-xs text-slate-500 mt-2">PDF, DOCX or TXT / up to 5 MB. Extracted technical summaries personalize your AI challenge; the file is discarded.</p><input aria-label="Upload resume" type="file" accept=".pdf,.docx,.txt" className="sr-only" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void act(async()=>{if(file.size>5*1024*1024)throw Error('Choose a file under 5 MB');const r=await api.uploadResume(file);setSkills(r.data.skills);setMessage(r.data.summary);setState({...state,journey:{...state.journey,resumeName:r.data.fileName}});});e.target.value='';}}/></label><GitHubIntegration/><h3 className="font-semibold">Confirm what you know or are learning</h3><p className="text-xs text-slate-500">Parsed skills are editable. Remove anything that does not describe you.</p><div className="flex flex-wrap gap-2">{skills.map(s=><button key={s} aria-label={`Remove ${s}`} onClick={()=>setSkills(skills.filter(x=>x!==s))} className="bg-indigo-50 dark:bg-indigo-950 text-indigo-500 rounded-lg px-3 py-2 text-xs">{s} ×</button>)}</div><form onSubmit={e=>{e.preventDefault();add(skill);}} className="flex gap-2"><input className={input} placeholder="Add a skill" aria-label="Add a skill" value={skill} maxLength={60} onChange={e=>setSkill(e.target.value)}/><button className="text-sm">Add</button></form><div className="flex flex-wrap gap-2">{['Java','Spring Boot','React','Python','SQL','Git','HTML','CSS'].filter(s=>!skills.includes(s)).map(s=><button key={s} onClick={()=>add(s)} className="border border-slate-200 dark:border-slate-700 rounded-lg px-3 py-2 text-xs">+ {s}</button>)}</div>{message&&<p className="text-xs text-slate-500">{message}</p>}</div>}
 {step===2&&<div className="space-y-5"><label className="block text-sm">Career direction<select className={`${input} mt-2`} value={track} onChange={e=>setTrack(e.target.value)}><option value="">Choose a track</option>{tracks.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="block text-sm">What would you like to build or improve?<textarea className={`${input} mt-2`} rows={3} maxLength={500} value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Build backend APIs and become confident with testing."/></label><label className="block text-sm">Weekly availability: {hours} hours<input className="block w-full mt-4 accent-indigo-500" type="range" min={1} max={40} value={hours} onChange={e=>setHours(+e.target.value)}/></label><p className="rounded-xl bg-indigo-50 dark:bg-indigo-950/40 p-4 text-sm">{trackName} · {skills.slice(0,3).join(', ')} · {hours}h/week</p></div>}
 {step===3&&<div className="space-y-5"><p className="text-sm text-slate-500">Optional 2–3 minute challenge for {trackName}. This gives a provisional starting level; code is not executed.</p>{challenge&&<p className="rounded-xl bg-indigo-50 dark:bg-indigo-950/40 p-4 text-xs">{challenge.source==='GEMINI'?'AI-personalized challenge':'Profile-based challenge - Live AI unavailable'}<br/>{challenge.context}{challenge.source==='PROFILE_FALLBACK'&&<><span className="block mt-2">{challenge.unavailableReason||'A saved fallback challenge is being shown. Retry live AI to check the current connection.'}</span><button disabled={challengeLoading||busy} className="underline mt-2" onClick={()=>void loadChallenge(true)}>Retry live AI</button></>}</p>}{!challengeLoading&&!challenge&&<button className={primary} onClick={()=>void loadChallenge()}>Retry challenge</button>}{!challengeLoading&&challenge?.questions.map((q,i)=><fieldset key={q.title}><legend className="text-sm font-semibold mb-2">{q.title}</legend>{q.options.map((o,n)=><label key={o} className="flex gap-3 items-center border border-slate-200 dark:border-slate-700 rounded-xl p-3 mt-2 text-sm"><input type="radio" name={`q${i}`} checked={answers[i]===n} onChange={()=>setAnswers(answers.map((v,j)=>i===j?n:v))}/>{o}</label>)}</fieldset>)}<label className="block text-sm">{challenge?.task}{challenge?.criteria.map(c=><span key={c} className="block mt-2 text-xs text-slate-500">- {c}</span>)}<textarea className={`${input} mt-3 font-mono`} rows={7} maxLength={10000} value={solution} onChange={e=>setSolution(e.target.value)}/></label><button disabled={busy||challengeLoading} className="text-sm underline text-indigo-500" onClick={()=>act(skip)}>Skip challenge and choose a beginner starting project</button></div>}
 {step===4&&<div className="space-y-4">{feedback&&<p className="text-sm bg-indigo-50 dark:bg-indigo-950/40 p-4 rounded-xl">{feedback}</p>}<p className="text-sm text-slate-500">Recommendations explain how your confirmed skills and selected track fit the project.</p>{state.recommendations.map(r=><button key={r.project.id} aria-pressed={project===r.project.id} onClick={()=>setProject(r.project.id)} className={`block w-full text-left p-5 rounded-2xl border ${project===r.project.id?'border-indigo-500 bg-indigo-50 dark:bg-indigo-950/30':'border-slate-200 dark:border-slate-700'}`}><span className="font-semibold">{r.project.name}</span><span className="float-right text-xs text-indigo-500">{r.matchScore}% fit</span><p className="mt-2 text-xs leading-5 text-slate-500">{r.reason}</p><p className="mt-3 text-xs">{r.project.technologies.join(' · ')}</p></button>)}{!state.recommendations.length&&<p>No active projects. Ask your admin to add one, then refresh.</p>}<div className="rounded-xl p-4 bg-slate-50 dark:bg-slate-950"><p className="text-sm font-semibold">Meet your Tech Lead</p><p className="mt-2 text-sm text-slate-500">Your DevSim Tech Lead will help with implementation, debugging and code review on {selected?.project.name||'your project'}.</p></div><fieldset className="space-y-2"><legend className="text-sm font-semibold mb-2">How should we get you started?</legend>{[{value:'AUTOMATED',title:'Start with this recommendation'},{value:'GUIDED',title:'Ask admin to guide me'}].map(o=><button key={o.value} aria-pressed={mode===o.value} onClick={()=>setMode(o.value as 'AUTOMATED'|'GUIDED')} className={`block w-full text-left border rounded-xl p-4 text-sm ${mode===o.value?'border-indigo-500':'border-slate-200 dark:border-slate-700'}`}>{o.title}</button>)}</fieldset>{mode==='GUIDED'&&<textarea aria-label="Message for admin" className={input} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)} placeholder="What guidance would help you-"/>}<FirstDayBrief state={{...state,journey:{...state.journey,preferredProjectId:project}}} name={user?.profile?.name||'Developer'} employeeId={user?.userId||''} preview/></div>}
 </div><footer className="mt-8 pt-5 border-t border-slate-200 dark:border-slate-800 flex justify-between"><button disabled={busy||step===0} className="text-sm text-slate-500 disabled:opacity-30 inline-flex gap-2 items-center" onClick={()=>setStep(step-1)}><ArrowLeft size={15}/>Back</button><button disabled={busy||(step===3&&(challengeLoading||!challenge))||(step===4&&!project)} className={primary} onClick={()=>act(step===4?finish:next)}>{busy?'Saving...':step===4?mode==='GUIDED'?'Send my request':'Create my welcome kit':'Continue'}<ArrowRight size={15}/></button></footer></>}
 </section></div></main>;
}
