package com.virtualcompany.modules.github;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.virtualcompany.modules.enrollment.repository.EnrollmentRepository;
import com.virtualcompany.modules.journey.JourneyRepository;
import com.virtualcompany.modules.ticket.repository.StudentTicketProgressRepository;
import com.virtualcompany.modules.ticket.service.TicketService;
import com.virtualcompany.common.exception.BadRequestException;
import org.junit.jupiter.api.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.util.ReflectionTestUtils;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.mockito.ArgumentCaptor;
import java.util.*;
class GithubWorkflowTest {
 JdbcTemplate db;GithubClient client;GithubCrypto crypto;GithubService service;JourneyRepository journeys;UUID user;
 @BeforeEach void setup(){db=mock(JdbcTemplate.class);client=mock(GithubClient.class);crypto=new GithubCrypto(Base64.getEncoder().encodeToString(new byte[32]));journeys=mock(JourneyRepository.class);service=new GithubService(mock(GithubRepositoryStore.class),db,crypto,client,mock(EnrollmentRepository.class),journeys,mock(StudentTicketProgressRepository.class),mock(TicketService.class),mock(GithubReviewer.class));user=UUID.randomUUID();ReflectionTestUtils.setField(service,"clientId","mock-client");ReflectionTestUtils.setField(service,"clientSecret","mock-secret");ReflectionTestUtils.setField(service,"callback","http://localhost:3000/github/callback");ReflectionTestUtils.setField(service,"webhookUrl","");ReflectionTestUtils.setField(service,"webhookSecret","");when(db.queryForList(contains("github_username as username"),eq(user))).thenReturn(List.of(Map.of("username","student")));}
 @Test void oauthUrlUsesPkceAndStoresHashedStateEncryptedVerifier(){String url=service.authUrl(user).get("url");assertTrue(url.contains("code_challenge_method=S256"));assertTrue(url.contains("admin%3Arepo_hook"));ArgumentCaptor<Object> hash=ArgumentCaptor.forClass(Object.class),verifier=ArgumentCaptor.forClass(Object.class);verify(db).update(eq("insert into github_oauth_states values(?,?,?,?)"),hash.capture(),eq(user),verifier.capture(),any());String state=url.split("&state=")[1].split("&")[0];assertEquals(GithubCrypto.hash(state),hash.getValue());assertTrue(url.contains(GithubCrypto.challenge(crypto.decrypt(verifier.getValue().toString()))));}
 @Test void callbackExchangesCodeAndEncryptsToken()throws Exception{var mapper=new ObjectMapper();when(db.queryForList(contains("delete from github_oauth_states"),eq(GithubCrypto.hash("state")),eq(user))).thenReturn(List.of(Map.of("verifier",crypto.encrypt("verifier"))));when(client.exchange(any())).thenReturn(mapper.readTree("{\"access_token\":\"mock-access-token\"}"));when(client.call(eq("mock-access-token"),eq("GET"),eq("/user"),isNull())).thenReturn(mapper.readTree("{\"id\":123,\"login\":\"student\",\"avatar_url\":\"https://avatars.githubusercontent.com/u/123\"}"));when(db.update(contains("update student_profiles set github_user_id"),any(),any(),any(),any(),any())).thenReturn(1);service.connect(user,"code","state");ArgumentCaptor<Object> encrypted=ArgumentCaptor.forClass(Object.class);verify(db).update(contains("update student_profiles set github_user_id"),eq("123"),eq("student"),any(),encrypted.capture(),eq(user));assertEquals("mock-access-token",crypto.decrypt(encrypted.getValue().toString()));assertNotEquals("mock-access-token",encrypted.getValue());}
 @Test void invalidStateNeverExchangesCode(){when(db.queryForList(contains("delete from github_oauth_states"),any(),eq(user))).thenReturn(List.of());assertThrows(BadRequestException.class,()->service.connect(user,"code","wrong-state"));verifyNoInteractions(client);}
 @Test void pendingAssignmentCannotProvision(){when(journeys.existsByUserIdAndStatus(user,"PENDING_REVIEW")).thenReturn(true);assertThrows(org.springframework.security.access.AccessDeniedException.class,()->service.provision(user,UUID.randomUUID()));verifyNoInteractions(client);}
 @Test void publicPortfolioOnlyIncludesApprovedMergedEvidence(){when(db.queryForList(contains("select e.github_repo_url as repository"),eq(user))).thenReturn(List.of(Map.of("verified",true,"pull_request","https://github.com/u/r/pull/1"),Map.of("verified",false,"pull_request","https://github.com/u/r/pull/2")));assertEquals(1,service.publicPortfolio(user).size());}
 @Test void syncLinksOwnTicketPrAndCompletesAfterAiApproval()throws Exception{
   UUID id=UUID.randomUUID();var owner=com.virtualcompany.modules.user.entity.User.builder().id(user).build();var profile=com.virtualcompany.modules.profile.entity.StudentProfile.builder().user(owner).build();var enrollment=com.virtualcompany.modules.enrollment.entity.StudentProjectEnrollment.builder().id(id).student(profile).build();
   var enrollmentRepo=(EnrollmentRepository)ReflectionTestUtils.getField(service,"enrollments");when(enrollmentRepo.findById(id)).thenReturn(Optional.of(enrollment));
   var ticket=com.virtualcompany.modules.ticket.entity.ProjectTicket.builder().id(UUID.randomUUID()).ticketKey("QK-101").acceptanceCriteria("Validate request input and add tests").build();var p=com.virtualcompany.modules.ticket.entity.StudentTicketProgress.builder().enrollment(enrollment).ticket(ticket).build();var progressRepo=(StudentTicketProgressRepository)ReflectionTestUtils.getField(service,"progress");when(progressRepo.findByEnrollmentId(id)).thenReturn(List.of(p));
   when(db.queryForMap(contains("github_repo_name as name"),eq(id))).thenReturn(Map.of("name","student/repo","url","https://github.com/student/repo"));when(db.queryForList(contains("select github_access_token"),eq(user))).thenReturn(List.of(Map.of("github_access_token",crypto.encrypt("token"))));when(db.queryForList(contains("select head_sha,review_status"),eq(id),eq(1))).thenReturn(List.of(),List.of(Map.of("head_sha","abc123","review_status","POSTED","approved",true,"review_body","All criteria passed")));
   var json=new ObjectMapper();var pr=json.readTree("{\"number\":1,\"html_url\":\"https://github.com/student/repo/pull/1\",\"state\":\"open\",\"user\":{\"login\":\"student\"},\"head\":{\"ref\":\"feature/qk-101-input\",\"sha\":\"abc123\",\"repo\":{\"full_name\":\"student/repo\"}}}");when(client.call(eq("token"),eq("GET"),contains("/pulls?state=all"),isNull())).thenReturn(json.createArrayNode().add(pr));when(client.call(eq("token"),eq("GET"),eq("/repos/student/repo/pulls/1/commits?per_page=100"),isNull())).thenReturn(json.createArrayNode());when(client.call(eq("token"),eq("GET"),eq("/repos/student/repo/pulls/1"),isNull())).thenReturn(json.readTree("{\"merged\":false}"));var reviewer=(GithubReviewer)ReflectionTestUtils.getField(service,"reviewer");when(reviewer.review(eq("token"),eq("student/repo"),eq(1),eq("abc123"),any())).thenReturn(new GithubReviewer.Review("POSTED","All criteria passed",true));
   service.sync(user,id);service.sync(user,id);assertEquals(com.virtualcompany.modules.ticket.entity.TicketStatus.DONE,p.getStatus());assertTrue(p.isReviewApproved());assertNotNull(p.getCompletedAt());verify(reviewer).review(eq("token"),eq("student/repo"),eq(1),eq("abc123"),any());verify(db,times(2)).update(contains("insert into github_pull_requests"),eq(id),eq(1),eq(ticket.getId()),eq("abc123"),eq("https://github.com/student/repo/pull/1"),eq("open"),eq(false));
 }
}
