package com.virtualcompany.modules.github;

import com.fasterxml.jackson.databind.*;
import com.virtualcompany.common.exception.BadRequestException;
import com.virtualcompany.modules.enrollment.repository.EnrollmentRepository;
import com.virtualcompany.modules.enrollment.entity.StudentProjectEnrollment;
import com.virtualcompany.modules.journey.JourneyRepository;
import com.virtualcompany.modules.ticket.repository.StudentTicketProgressRepository;
import com.virtualcompany.modules.ticket.entity.TicketStatus;
import com.virtualcompany.modules.ticket.service.TicketService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;
import java.time.*;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;

@Service
@RequiredArgsConstructor
public class GithubService {
    private final GithubRepositoryStore store; private final JdbcTemplate db; private final GithubCrypto crypto; private final GithubClient github;
    private final EnrollmentRepository enrollments;private final JourneyRepository journeys;
    private final StudentTicketProgressRepository progress;private final TicketService tickets;
    @Value("${github.app-slug:}") private String appSlug="";
    @Value("${github.client-id:}") private String clientId;
    @Value("${github.client-secret:}") private String clientSecret;
    @Value("${github.callback-url:http://localhost:3000/github/callback}") private String callback;
    @Value("${github.webhook-url:}") private String webhookUrl;
    @Value("${github.webhook-secret:}") private String webhookSecret;
    @Value("${github.template:}") private String template;
    @Value("${github.repo-mode:TEMPLATE}") private String repoMode;
    private void allowed(UUID user){if(journeys.existsByUserIdAndStatus(user,"PENDING_REVIEW"))throw new org.springframework.security.access.AccessDeniedException("Assignment is awaiting approval");}
    private StudentProjectEnrollment owned(UUID user,UUID id){allowed(user);var e=enrollments.findById(id).orElseThrow(()->new BadRequestException("Enrollment not found"));if(!e.getStudent().getUser().getId().equals(user))throw new org.springframework.security.access.AccessDeniedException("Workspace belongs to another student");return e;}
    public Map<String,Object> account(UUID user){var rows=db.queryForList("select github_username as username, github_avatar_url as avatar, github_connected_at as connected_at from student_profiles where user_id=?",user);var out=new HashMap<String,Object>();if(appSlug.matches("[a-z0-9-]+"))out.put("botInstallUrl","https://github.com/apps/"+appSlug+"/installations/new");out.put("configured",!clientId.isBlank()&&!clientSecret.isBlank()&&crypto.configured());out.put("connected",!rows.isEmpty()&&rows.getFirst().get("username")!=null);if(!rows.isEmpty())out.putAll(rows.getFirst());return out;}
    @Transactional public Map<String,String> authUrl(UUID user){if(!Boolean.TRUE.equals(account(user).get("configured")))throw new BadRequestException("Configure GitHub OAuth and token encryption on the backend first");db.update("delete from github_oauth_states where expires_at < now() or user_id=?",user);String state=GithubCrypto.random(),verifier=GithubCrypto.random();db.update("insert into github_oauth_states values(?,?,?,?)",GithubCrypto.hash(state),user,crypto.encrypt(verifier),java.sql.Timestamp.from(Instant.now().plusSeconds(600)));return Map.of("url","https://github.com/login/oauth/authorize?client_id="+enc(clientId)+"&redirect_uri="+enc(callback)+"&scope="+enc("repo read:user admin:repo_hook")+"&state="+state+"&code_challenge="+GithubCrypto.challenge(verifier)+"&code_challenge_method=S256");}
    @Transactional public void connect(UUID user,String code,String state){var rows=db.queryForList("delete from github_oauth_states where state_hash=? and user_id=? and expires_at>now() returning verifier",GithubCrypto.hash(state),user);if(rows.isEmpty())throw new BadRequestException("OAuth state expired or invalid. Reconnect GitHub.");var token=github.exchange(Map.of("client_id",clientId,"client_secret",clientSecret,"code",code,"redirect_uri",callback,"code_verifier",crypto.decrypt(rows.getFirst().get("verifier").toString())));if(token==null||!token.hasNonNull("access_token"))throw new BadRequestException("GitHub did not authorize this connection");String access=token.path("access_token").asText();var me=github.call(access,"GET","/user",null);if(db.update("update student_profiles set github_user_id=?,github_username=?,github_avatar_url=?,github_access_token=?,github_connected_at=now() where user_id=?",me.path("id").asText(),me.path("login").asText(),me.path("avatar_url").asText(),crypto.encrypt(access),user)!=1)throw new BadRequestException("Student profile required");}
    public void disconnect(UUID user){db.update("update student_profiles set github_user_id=null,github_username=null,github_avatar_url=null,github_access_token=null,github_connected_at=null where user_id=?",user);db.update("delete from github_oauth_states where user_id=?",user);}
    private String token(UUID user){var r=db.queryForList("select github_access_token from student_profiles where user_id=?",user);if(r.isEmpty()||r.getFirst().get("github_access_token")==null)throw new BadRequestException("Connect GitHub first");return crypto.decrypt(r.getFirst().get("github_access_token").toString());}
    private Map<String,Object> repo(UUID id){return db.queryForMap("select github_repo_name as name,github_repo_url as url,active_pr_url as active_pr_url from student_project_enrollments where id=?",id);}
    @Transactional public synchronized Map<String,Object> provision(UUID user,UUID id){var e=owned(user,id);if(repo(id).get("name")!=null)return workspace(user,id);String access=token(user),login=account(user).get("username").toString();String name="devsim-"+e.getProject().getSlug()+"-"+id.toString().substring(0,8);String projectTemplate=e.getProject().getGithubTemplateRepo();String selectedTemplate=projectTemplate==null||projectTemplate.isBlank()?template:projectTemplate;String selectedMode=projectTemplate==null||projectTemplate.isBlank()?repoMode:e.getProject().getGithubRepoMode();JsonNode result;
        if(!selectedTemplate.isBlank()){if(!selectedTemplate.matches("[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+"))throw new BadRequestException("Invalid GitHub template setting");result=selectedMode.equalsIgnoreCase("FORK")?github.call(access,"POST","/repos/"+selectedTemplate+"/forks",Map.of("name",name,"default_branch_only",true)):github.call(access,"POST","/repos/"+selectedTemplate+"/generate",Map.of("owner",login,"name",name,"private",false,"description","DevSim: "+e.getProject().getName()));}
        else{result=github.call(access,"POST","/user/repos",Map.of("name",name,"private",false,"auto_init",true,"description","DevSim: "+e.getProject().getName()));}
        String full=result.path("full_name").asText();store.record(id,full,result.path("html_url").asText());
        return finishSetup(user,id);
    }
    @Transactional public Map<String,Object> finishSetup(UUID user,UUID id){var e=owned(user,id);String full=Objects.toString(repo(id).get("name"),"");if(full.isBlank())throw new BadRequestException("Provision the repository first");String access=token(user);tickets.getWorkspace(id);
        String readme="# "+e.getProject().getName()+"\n\n"+e.getProject().getDescription()+"\n\n## DevSim ticket workflow\nClone this repository. Create a feature branch using the exact ticket key below. Push changes and open a PR against the default branch. DevSim links PRs authored by your connected GitHub account automatically.\n\n";
        for(var p:progress.findByEnrollmentId(id))readme+="### "+p.getTicket().getTicketKey()+": "+p.getTicket().getTitle()+"\nBranch: `feature/"+p.getTicket().getTicketKey().toLowerCase(Locale.ROOT)+"`\n\n"+p.getTicket().getAcceptanceCriteria()+"\n\n";
        var root=github.call(access,"GET","/repos/"+full+"/contents",null);String sha="";for(var file:root)if(file.path("name").asText().equals("DEVSIM.md"))sha=file.path("sha").asText();var content=new HashMap<String,Object>();content.put("message","Configure DevSim ticket workspace");content.put("content",Base64.getEncoder().encodeToString(readme.getBytes(StandardCharsets.UTF_8)));if(!sha.isBlank())content.put("sha",sha);github.call(access,"PUT","/repos/"+full+"/contents/DEVSIM.md",content);
        var refs=github.call(access,"GET","/repos/"+full+"/git/matching-refs/heads/devsim/start",null);if(refs.isEmpty()){var info=github.call(access,"GET","/repos/"+full,null);var head=github.call(access,"GET","/repos/"+full+"/git/ref/heads/"+info.path("default_branch").asText(),null);github.call(access,"POST","/repos/"+full+"/git/refs",Map.of("ref","refs/heads/devsim/start","sha",head.path("object").path("sha").asText()));}
        if(!webhookUrl.isBlank()&&!webhookSecret.isBlank()){var hooks=github.call(access,"GET","/repos/"+full+"/hooks",null);boolean found=false;for(var h:hooks)if(h.path("config").path("url").asText().equals(webhookUrl))found=true;if(!found)github.call(access,"POST","/repos/"+full+"/hooks",Map.of("name","web","active",true,"events",List.of("pull_request","push"),"config",Map.of("url",webhookUrl,"content_type","json","secret",webhookSecret,"insecure_ssl","0")));}
        return workspace(user,id);
    }
    public Map<String,Object> workspace(UUID user,UUID id){owned(user,id);var out=new HashMap<String,Object>(repo(id));out.put("pullRequests",db.queryForList("select ticket_id,pr_number,url,state,review_status,review_body,approved,merged,head_sha from github_pull_requests where enrollment_id=? order by updated_at desc",id));out.put("branches",progress.findByEnrollmentId(id).stream().map(p->Map.of("ticket",p.getTicket().getTicketKey(),"branch","feature/"+p.getTicket().getTicketKey().toLowerCase(Locale.ROOT))).toList());out.put("webhookConfigured",!webhookUrl.isBlank()&&!webhookSecret.isBlank());return out;}
    @Transactional public Map<String,Object> sync(UUID user,UUID id){owned(user,id);db.queryForList("select id from student_project_enrollments where id=? for update",id);String full=Objects.toString(repo(id).get("name"),"");if(full.isBlank())throw new BadRequestException("Setup GitHub workspace first");String access=token(user);var prs=github.call(access,"GET","/repos/"+full+"/pulls?state=all&per_page=100",null);for(var pr:prs)track(user,id,full,access,pr);return workspace(user,id);}
    private final GithubReviewer reviewer;
    private void track(UUID user,UUID id,String full,String access,JsonNode pr){if(!pr.path("user").path("login").asText().equalsIgnoreCase(account(user).get("username").toString()))return;if(!pr.path("head").path("repo").path("full_name").asText().equalsIgnoreCase(full))return;
        String branch=pr.path("head").path("ref").asText();for(var p:progress.findByEnrollmentId(id)){String expected="feature/"+p.getTicket().getTicketKey().toLowerCase(Locale.ROOT);if(!branch.equalsIgnoreCase(expected)&&!branch.toLowerCase(Locale.ROOT).startsWith(expected+"-"))continue;
            int number=pr.path("number").asInt();String sha=pr.path("head").path("sha").asText();var old=db.queryForList("select head_sha,review_status,approved,review_body from github_pull_requests where enrollment_id=? and pr_number=?",id,number);boolean fresh=old.isEmpty()||!sha.equals(old.getFirst().get("head_sha"));
            var detail=github.call(access,"GET","/repos/"+full+"/pulls/"+number,null);boolean merged=detail.path("merged").asBoolean();
            db.update("insert into github_pull_requests(enrollment_id,pr_number,ticket_id,head_sha,url,state,merged) values(?,?,?,?,?,?,?) on conflict(enrollment_id,pr_number) do update set head_sha=excluded.head_sha,state=excluded.state,merged=excluded.merged,approved=case when github_pull_requests.head_sha=excluded.head_sha then github_pull_requests.approved else false end,review_status=case when github_pull_requests.head_sha=excluded.head_sha then github_pull_requests.review_status else 'PENDING' end,updated_at=now()",id,number,p.getTicket().getId(),sha,pr.path("html_url").asText(),pr.path("state").asText(),merged);
            if(fresh){var commitList=github.call(access,"GET","/repos/"+full+"/pulls/"+number+"/commits?per_page=100",null);List<Map<String,String>> history=new ArrayList<>();for(var c:commitList){String msg=c.path("commit").path("message").asText().split("\\n")[0];history.add(Map.of("sha",c.path("sha").asText(),"url",c.path("html_url").asText(),"message",msg.substring(0,Math.min(300,msg.length())),"author",c.path("author").path("login").asText()));}try{db.update("update github_pull_requests set commits_json=? where enrollment_id=? and pr_number=?",new ObjectMapper().writeValueAsString(history),id,number);}catch(com.fasterxml.jackson.core.JsonProcessingException ex){throw new BadRequestException("Commit evidence could not be saved");}}
            db.update("update student_project_enrollments set active_pr_url=?,active_pr_number=? where id=?",pr.path("html_url").asText(),number,id);
            if(fresh){p.setStatus(TicketStatus.IN_REVIEW);p.setCompletedAt(null);p.setReviewApproved(false);p.setAiReviewFeedback(null);progress.save(p);}
            if(pr.path("state").asText().equals("open")){boolean previousApproved=!fresh&&!old.isEmpty()&&Boolean.TRUE.equals(old.getFirst().get("approved"));p.setStatus(previousApproved?TicketStatus.DONE:TicketStatus.IN_REVIEW);p.setCompletedAt(previousApproved?(p.getCompletedAt()==null?Instant.now():p.getCompletedAt()):null);p.setReviewApproved(previousApproved);progress.save(p);
                if(fresh||!old.isEmpty()&&!Objects.equals(old.getFirst().get("review_status"),"POSTED")){var review=reviewer.review(access,full,number,sha,p.getTicket().getAcceptanceCriteria());db.update("update github_pull_requests set review_status=?,review_body=?,approved=? where enrollment_id=? and pr_number=?",review.status(),review.body(),review.approved(),id,number);p.setAiReviewFeedback(review.body());progress.save(p);if(review.approved()){p.setReviewApproved(true);p.setStatus(TicketStatus.DONE);p.setCompletedAt(Instant.now());p.setAiReviewFeedback(review.body());progress.save(p);}}
            }break;
        }
    }
    @Transactional public void processWebhook(String payload){try{var event=new ObjectMapper().readTree(payload);String full=event.path("repository").path("full_name").asText();if(full.isBlank())return;var rows=db.queryForList("select e.id,p.user_id from student_project_enrollments e join student_profiles p on p.id=e.student_id where e.github_repo_name=? and p.github_access_token is not null",full);for(var r:rows)sync((UUID)r.get("user_id"),(UUID)r.get("id"));}catch(java.io.IOException e){throw new BadRequestException("Invalid webhook body");}}
    public List<Map<String,Object>> portfolio(UUID user){return db.queryForList("select e.github_repo_url as repository,g.url as pull_request,g.head_sha,g.merged,g.approved,g.commits_json,t.ticket_key,t.title,(g.merged and g.approved) as verified from github_pull_requests g join student_project_enrollments e on e.id=g.enrollment_id join student_profiles p on p.id=e.student_id join project_tickets t on t.id=g.ticket_id where p.user_id=? order by g.updated_at desc",user);}
    public List<Map<String,Object>> publicPortfolio(UUID user){return portfolio(user).stream().filter(r->Boolean.TRUE.equals(r.get("verified"))).toList();}
    private static String enc(String s){return URLEncoder.encode(s,StandardCharsets.UTF_8);}
}
