ALTER TABLE users ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE student_journeys ADD COLUMN assessment_skipped BOOLEAN NOT NULL DEFAULT FALSE;
CREATE TABLE registration_verifications (user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, code_hash VARCHAR(64) NOT NULL, expires_at TIMESTAMPTZ NOT NULL, sent_at TIMESTAMPTZ NOT NULL, attempts INTEGER NOT NULL DEFAULT 0);
