INSERT INTO career_tracks (id, name, slug, description) VALUES
 ('11111111-1111-1111-1111-111111111112','Frontend Developer','frontend-developer','Build accessible interfaces with React, TypeScript, CSS and automated UI tests.'),
 ('11111111-1111-1111-1111-111111111113','Python Backend Developer','python-backend-developer','Build Python services with Django, SQL and practical API testing.')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO projects (id, company_id, career_track_id, name, slug, short_description, description, difficulty, estimated_duration) VALUES
 ('33333333-3333-3333-3333-333333333334',NULL,'11111111-1111-1111-1111-111111111111','CareFlow Appointment API','careflow-appointment-api','Help a clinic manage doctors, appointments and booking conflicts.','Business brief: A clinic currently uses spreadsheets and suffers double bookings. Build doctor listings, appointment creation and validation. Milestones: 1. Doctor directory; 2. Validated booking workflow; 3. Conflict handling and integration tests. Start with Java 21 and Spring Boot, connect PostgreSQL and document API setup. Deliver a repository containing implementation, tests and README. No pre-existing repository is bundled.', 'BEGINNER','4 weeks'),
 ('33333333-3333-3333-3333-333333333335',NULL,'11111111-1111-1111-1111-111111111112','LearnSpace Student Portal','learnspace-student-portal','Build a responsive course directory and student progress dashboard.','Business brief: Students need one place to discover courses and track their learning. Build a React interface with accessible navigation, course filtering, loading/empty states and a progress dashboard. Milestones: 1. Responsive course listing; 2. Validated enrollment form; 3. Dashboard and component tests. Create a TypeScript React project, use fixture data initially and document setup. Deliver implementation, tests and README. No pre-existing repository is bundled.', 'BEGINNER','3 weeks'),
 ('33333333-3333-3333-3333-333333333336',NULL,'11111111-1111-1111-1111-111111111113','SpendWise Expense Service','spendwise-expense-service','Create a personal expense API with categories, budgets and monthly summaries.','Business brief: Freelancers need to track expenses against monthly budgets. Build validated expense entries, category filtering and monthly summaries. Milestones: 1. Expense listing; 2. Validated creation and updates; 3. Budget calculations and tests. Start a Django project, use PostgreSQL and provide documented API examples. Deliver implementation, tests and README. No pre-existing repository is bundled.', 'BEGINNER','4 weeks'),
 ('33333333-3333-3333-3333-333333333337',NULL,'11111111-1111-1111-1111-111111111111','StockPilot Inventory Service','stockpilot-inventory-service','Prevent overselling with stock reservations, audit trails and concurrent updates.','Business brief: A warehouse oversells products during simultaneous orders. Implement catalog pagination, stock reservations, atomic inventory changes, authorization and audit logs. Milestones: 1. Validated inventory API; 2. Concurrency-safe reservations; 3. Integration and performance tests. Start a Spring Boot service with PostgreSQL. Deliver a documented repository with reproducible tests. No pre-existing repository is bundled.', 'INTERMEDIATE','6 weeks')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO project_technologies (project_id, technology_name)
SELECT p.id, t.name FROM (VALUES
 ('careflow-appointment-api','Java'),('careflow-appointment-api','Spring Boot'),('careflow-appointment-api','PostgreSQL'),('careflow-appointment-api','JUnit'),
 ('learnspace-student-portal','React'),('learnspace-student-portal','TypeScript'),('learnspace-student-portal','CSS'),('learnspace-student-portal','Jest'),
 ('spendwise-expense-service','Python'),('spendwise-expense-service','Django'),('spendwise-expense-service','PostgreSQL'),('spendwise-expense-service','Git'),
 ('stockpilot-inventory-service','Java'),('stockpilot-inventory-service','Spring Boot'),('stockpilot-inventory-service','PostgreSQL'),('stockpilot-inventory-service','Redis')
) AS t(slug,name) JOIN projects p ON p.slug=t.slug ON CONFLICT (project_id, technology_name) DO NOTHING;
