'use client';
import {useEffect,useRef} from 'react';
import {X,FastForward,CheckCircle2} from 'lucide-react';
import {usePipelineRunner,PipelineResult} from './usePipelineRunner';
import {PipelineStageNode} from './PipelineStageNode';
import {PipelineConsoleLogs} from './PipelineConsoleLogs';
import {PipelineReviewSummary} from './PipelineReviewSummary';
export function PipelineModal({ticketKey,code,mode,run,onClose,onRerun,onNext}:{ticketKey:string;code:string;mode:'code'|'github';run:()=>Promise<PipelineResult>;onClose:()=>void;onRerun:()=>void;onNext?:()=>void}){
 const pipeline=usePipelineRunner(run,code,mode);const panel=useRef<HTMLDivElement>(null);const finished=pipeline.status!=='RUNNING';
 useEffect(()=>{const previous=document.activeElement as HTMLElement;panel.current?.focus();const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old;previous?.focus();};},[]);
 return <div className="fixed inset-0 z-[100] bg-slate-950/80 backdrop-blur-sm flex items-center justify-center p-2 sm:p-6"><div ref={panel} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="pipeline-title" onKeyDown={e=>{if(e.key==='Escape'&&finished)onClose();if(e.key==='Tab'){const nodes=panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,summary,[tabindex="0"]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===panel.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===panel.current)){e.preventDefault();first.focus();}}}} className="w-full max-w-4xl max-h-[94vh] overflow-auto rounded-2xl border border-slate-700 bg-slate-950 text-slate-100 shadow-2xl outline-none"><header className="p-5 border-b border-slate-800 flex justify-between gap-4"><div><p className="text-xs tracking-widest text-cyan-400 uppercase">DevSim engineering pipeline</p><h2 id="pipeline-title" className="mt-2 font-mono text-lg">Pipeline #build-{ticketKey}-run</h2><p className="text-xs mt-2 text-slate-400" role="status">{pipeline.status} · {pipeline.elapsed.toFixed(1)}s</p></div><button disabled={!finished} aria-label="Close pipeline" onClick={onClose} className="self-start p-2 disabled:opacity-25"><X size={20}/></button></header><div className="p-5 space-y-5"><p className="text-xs text-slate-400">Training simulation for lint, security, tests and staging. Backend review determines approval. Skip Animation never skips verification.</p><ol aria-label="Pipeline stages" className="grid sm:grid-cols-5 gap-2">{pipeline.stages.map((stage,i)=><PipelineStageNode key={stage.name} stage={stage} index={i}/>)}</ol>{pipeline.status==='PASSED'&&<div className="flex gap-3 items-center rounded-xl p-4 bg-emerald-500/15 text-emerald-300 motion-safe:animate-pulse"><CheckCircle2/>Ticket completed! Sprint progress updated.</div>}<PipelineConsoleLogs logs={pipeline.logs}/>{pipeline.result&&<PipelineReviewSummary result={pipeline.result}/>}<footer className="flex flex-wrap justify-end gap-3">{!finished?<button onClick={pipeline.skip} className="flex gap-2 items-center rounded-lg border border-slate-600 px-4 py-2 text-sm"><FastForward size={16}/>Skip Animation</button>:<>{pipeline.status==='PASSED'&&onNext&&<button onClick={onNext} className="rounded-lg border border-emerald-500 px-4 py-2 text-sm">Open next ticket</button>}{pipeline.status==='FAILED'&&<button onClick={onRerun} className="rounded-lg border border-slate-600 px-4 py-2 text-sm">Re-run</button>}<button onClick={onClose} className="rounded-lg bg-cyan-600 px-4 py-2 text-sm">{pipeline.status==='FAILED'?'Fix code':'Back to workspace'}</button></>}</footer></div></div></div>;
}
