'use client';
import React, { useEffect, useState } from 'react';
import { api } from '@/lib/api/client';
import type { Project } from '@/lib/types';
import type { AssignmentRequest } from '@/lib/journey';
import { Check, Clock, RefreshCw, X } from 'lucide-react';

export function AssignmentRequests({ projects, onReviewed }: { projects: Project[]; onReviewed: () => void }) {
  const [requests, setRequests] = useState<AssignmentRequest[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(''); const [choices, setChoices] = useState<Record<string, string>>({}); const [notes, setNotes] = useState<Record<string, string>>({});
  async function load() { setLoading(true); setError(''); try { const r = await api.getAssignmentRequests(); setRequests(r.data); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function review(r: AssignmentRequest, approve: boolean) {
    setBusy(r.userId); setError('');
    try { await api.reviewAssignment(r.userId, { projectId: choices[r.userId] || r.journey.preferredProjectId || '', approve, note: notes[r.userId] || '' }); await load(); onReviewed(); }
    catch (e) { setError((e as Error).message); } finally { setBusy(''); }
  }
  return <section className="mb-6 rounded-2xl border border-slate-700 bg-slate-900/70 p-5 text-white"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 font-semibold"><Clock size={18} className="text-amber-400" />Guided assignment requests <span className="rounded-full bg-amber-400/10 px-2 py-0.5 text-xs text-amber-300">{requests.length}</span></h2><button aria-label="Refresh assignment requests" onClick={load} disabled={loading}><RefreshCw size={16} className={loading ? 'animate-spin' : ''} /></button></div>{error && <p role="alert" className="mt-3 text-sm text-red-300">{error}</p>}{!loading && !requests.length && <p className="mt-3 text-sm text-slate-400">All caught up. Guided onboarding requests appear here.</p>}<div className="mt-4 space-y-4">{requests.map(r => <article key={r.userId} className="rounded-xl border border-slate-700 bg-slate-950/50 p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{r.name}<span className="ml-2 text-xs font-normal text-slate-400">{r.email}</span></h3><span className="text-xs text-amber-300">Assessment {r.journey.assessmentScore}/100 · {r.journey.weeklyHours}h/week</span></div><p className="mt-2 text-sm text-slate-300">Goal: {r.journey.goal}</p><p className="mt-1 text-xs text-indigo-300">Skills: {r.journey.skills}</p>{r.journey.requestNote && <p className="mt-2 text-sm text-slate-400">Student note: {r.journey.requestNote}</p>}<details className="mt-3 text-xs text-slate-400"><summary className="cursor-pointer">View starter submission</summary><pre className="mt-2 max-h-44 overflow-auto whitespace-pre-wrap">{r.journey.assessmentAnswer}</pre></details><div className="mt-4 grid gap-3 md:grid-cols-2"><select aria-label={`Project for ${r.name}`} className="rounded-lg border border-slate-700 bg-slate-950 p-3 text-sm" value={choices[r.userId] || r.journey.preferredProjectId || ''} onChange={e => setChoices({ ...choices, [r.userId]: e.target.value })}><option value="">Choose project</option>{projects.map(p => <option key={p.id} value={p.id}>{p.name} · {p.difficulty}</option>)}</select><input aria-label={`Admin feedback for ${r.name}`} className="rounded-lg border border-slate-700 bg-slate-950 p-3 text-sm" maxLength={2000} value={notes[r.userId] || ''} onChange={e => setNotes({ ...notes, [r.userId]: e.target.value })} placeholder="Feedback (required when requesting changes)" /></div><div className="mt-3 flex gap-3"><button disabled={!!busy} onClick={() => review(r, true)} className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-xs disabled:opacity-40"><Check size={14} />{busy === r.userId ? 'Saving…' : 'Approve & assign tickets'}</button><button disabled={!!busy} onClick={() => review(r, false)} className="inline-flex items-center gap-2 rounded-lg border border-slate-700 px-4 py-2 text-xs disabled:opacity-40"><X size={14} />Request changes</button></div></article>)}</div></section>;
}
