'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,ArrowDown,Download,Mail,Github,Linkedin,Check,Copy,Menu,X} from 'lucide-react';
import {portfolio} from '@/lib/portfolio';
import {GitHubPortfolio} from './GitHubPortfolio';
import styles from './ClassicPortfolio.module.css';
const experience=[
 {period:'2025 — Present',company:'HTI Infosystems',role:'Java Backend Engineer',description:'Building the backend of HRIMS, a multi-tenant B2B SaaS platform for HR and recruitment.',points:['Core application, candidate and recruitment microservices with Spring Boot, PostgreSQL and Kafka.','Recruitment stage transitions, offer-lifecycle state machines, SLA detection and automated stage-entry actions.','Gateway JWT validation, trusted headers and AOP-driven role and organization authorization.','Organization-scoped Redis caching, Redis Streams security events and candidate privacy workflows.'],tags:['Spring Boot','Cloud Gateway','Kafka','Redis','PostgreSQL']},
 {period:'Apr — Jul 2025',company:'Elegance',role:'Java Intern',description:'Strengthened the fundamentals behind data-driven Java applications.',points:['JDBC-based CRUD operations for application modules.','Servlets for HTTP requests, sessions and form processing.'],tags:['Java','JDBC','Servlets']},
 {period:'Jan — Feb 2025',company:'Techmaa IT Services',role:'Backend Developer Intern · Noida',description:'Built REST APIs for a Hospital Management System covering patients, doctors, appointments and billing.',points:['Layered Controller–Service–Repository architecture.','Request validation, error handling and database integration; API testing with Postman and Swagger.'],tags:['REST APIs','JDBC','Postman','Swagger']}
];
const toolkit=[{title:'The core',text:'Java · SQL · JavaScript',detail:'The languages I build with.'},{title:'The backend',text:'Spring Boot · Spring Security · WebFlux · Spring AOP · JDBC',detail:'APIs, gateways and application services.'},{title:'The architecture',text:'Microservices · Multi-tenancy · Event-driven design · MVC',detail:'Clear boundaries and dependable data flows.'},{title:'The data layer',text:'PostgreSQL · MySQL · Redis · Kafka · Redis Streams',detail:'Persistence, caching and asynchronous messaging.'},{title:'The trust layer',text:'JWT · JWKS · RS256 · ES256 · Role & organization authorization',detail:'Security across gateways and services.'},{title:'The workflow',text:'Git · Maven · Postman · Swagger · Eureka',detail:'Development, integration and API tooling.'}];
export function DeveloperPortfolio({studentId}:{studentId?:string}={}){
 const [copied,setCopied]=useState(false);const [copyError,setCopyError]=useState('');const [menu,setMenu]=useState(false);
 if(studentId)return <GitHubPortfolio studentId={studentId}/>;
 async function copyEmail(){try{await navigator.clipboard.writeText(portfolio.email);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{setCopyError('Copy the email address shown below.');}}
 return <div className={`${styles.root} classic-portfolio`}>
 <header className={styles.header}><a href="#top" className={styles.brand}><span className={styles.monogram}>sd.</span><span>Sarthak Dhanotiya<span className={styles.brandCaption}>JAVA BACKEND ENGINEER</span></span></a><nav aria-label="Portfolio navigation" className={`${styles.nav} ${menu?styles.navOpen:''}`}><a href="#work" onClick={()=>setMenu(false)}>Selected work</a><a href="#about" onClick={()=>setMenu(false)}>About</a><a href="#contact" onClick={()=>setMenu(false)}>Let’s talk <ArrowUpRight size={14}/></a></nav><button className={styles.mobileMenu} aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X size={22}/>:<Menu size={22}/>}</button></header>
 <main id="top" className={styles.main}>
 <section className={styles.hero}><div className={styles.heroText}><p className={styles.eyebrow}><span className={styles.dot}/>JAVA BACKEND ENGINEER</p><h1 className={styles.name}>Sarthak<br/><em>Dhanotiya.</em></h1><p className={styles.heroTitle}>Good software starts<br/>with a thoughtful backend.</p><p className={styles.lead}>I build secure APIs, event-driven microservices and systems that keep complex workflows moving. Java at the core. Clarity in every layer.</p><div className={styles.actions}><a className={styles.primary} href="#work">Explore my work <ArrowDown size={16}/></a><a className={styles.secondary} href={portfolio.resumeUrl} download>Download résumé <Download size={16}/></a></div><div className={styles.heroFoot}><span>Currently building at <strong>HTI Infosystems</strong></span><span>01 / INTRODUCTION</span></div></div><div className={styles.portraitWrap}><div className={styles.photoFrame}><img src={portfolio.imageUrl} alt="Sarthak Dhanotiya outdoors" width={1821} height={2427} className={styles.photo} fetchPriority="high"/><span className={styles.photoStamp}>THE PERSON<br/>BEHIND THE CODE.</span></div><div className={styles.photoCaption}><span>A little curiosity.<br/>A lot of building.</span><span className={styles.signature}>Sarthak.</span></div><span className={styles.verticalCaption}>JAVA / SYSTEMS / CRAFT</span></div></section>
 <div className={styles.ribbon}><span>SECURE BY DESIGN</span><span>✳</span><span>EVENT-DRIVEN SYSTEMS</span><span>✳</span><span>BUILT WITH INTENTION</span><span>✳</span><span>JAVA & SPRING</span></div>
 <section id="work" className={styles.section}><div className={styles.sectionHeading}><p className={styles.eyebrow}>02 / SELECTED WORK</p><h2>Systems with<br/><em>a purpose.</em></h2><p>Professional engineering and personal builds.<br/>Different problems. The same care.</p></div>
 <article className={`${styles.feature} ${styles.featureDark}`}><div className={styles.featureCopy}><p className={styles.projectLabel}>01 / PROFESSIONAL WORK · HTI INFOSYSTEMS</p><h3>HRIMS<span>Complex workflows.<br/>Clear foundations.</span></h3><p>A multi-tenant HR and recruitment platform. My work spans candidate and application services, recruitment pipelines, gateway security and organization-scoped caching.</p><div className={styles.tags}>{['Spring Boot','Kafka','PostgreSQL','Redis','WebFlux'].map(t=><span key={t}>{t}</span>)}</div><a href="#experience" className={styles.textLink}>Explore my contribution <ArrowUpRight size={17}/></a></div><div className={styles.systemDiagram} aria-label="Illustrative HRIMS architecture"><div className={styles.diagramTop}><span className={styles.dot}/>SYSTEM NOTES / 001</div><div className={styles.diagramGateway}>Cloud Gateway <span>JWT validation · trusted headers</span></div><div className={styles.diagramLine}/><div className={styles.diagramServices}><span>Applications</span><span>Candidates</span><span>Recruitment</span></div><div className={styles.diagramLine}/><div className={styles.diagramBottom}><span>Kafka<span>Events</span></span><span>PostgreSQL<span>Data</span></span><span>Redis<span>Cache & streams</span></span></div><p>Organization-aware services.<br/>Explicit authorization boundaries.</p></div></article>
 <div className={styles.projectGrid}><article className={styles.project}><span className={styles.projectLabel}>02 / PERSONAL PROJECT</span><div className={styles.teaVisual} aria-hidden="true"><span className={styles.steam}>~ ~ ~</span><span className={styles.cup}>☕</span><span className={styles.teaWord}>Medicine<br/><em>Chai.</em></span></div><h3>Medicine Chai</h3><p>A mobile-friendly ordering application with cart management and a dynamic React interface, backed by Spring Boot REST APIs.</p><div className={styles.tags}><span>React</span><span>Spring Boot</span><span>REST APIs</span></div><p className={styles.projectNote}>Frontend and backend, brought together through JSON APIs and CORS.</p></article><article className={styles.project}><span className={styles.projectLabel}>03 / CURRENT BUILD</span><Link href="/" className={styles.devsimVisual} aria-label="Explore DevSim"><span className={styles.terminalTop}>● ● ● <span>devsim / workspace</span></span><span className={styles.terminalCode}><span>$ start developer.journey</span><br/>✓ Personalized project<br/>✓ Real engineering tickets<br/>✓ Code review pipeline<br/><span className={styles.terminalPrompt}>Ready for your first day. _</span></span></Link><h3>DevSim <Link href="/" aria-label="Open DevSim"><ArrowUpRight size={22}/></Link></h3><p>A virtual company workspace for students to practice tickets, code reviews and project delivery, with personalized onboarding and GitHub workflows.</p><div className={styles.tags}><span>Java</span><span>Spring Boot</span><span>Next.js</span><span>PostgreSQL</span></div><Link href="/" className={styles.textLink}>Explore the platform <ArrowUpRight size={16}/></Link></article></div></section>
 <section id="experience" className={styles.section}><div className={styles.sectionHeading}><p className={styles.eyebrow}>03 / EXPERIENCE</p><h2>Learning by<br/><em>building.</em></h2><p>From Java fundamentals to<br/>real-world backend systems.</p></div><div className={styles.timeline}>{experience.map((job,i)=><article className={styles.job} key={job.company}><div className={styles.jobMeta}><span className={styles.jobIndex}>0{i+1}</span><p>{job.period}</p></div><div><h3>{job.company}</h3><p className={styles.role}>{job.role}</p><p className={styles.jobDescription}>{job.description}</p><ul>{job.points.map(point=><li key={point}>{point}</li>)}</ul><div className={styles.tags}>{job.tags.map(t=><span key={t}>{t}</span>)}</div></div></article>)}</div></section>
 <section id="about" className={`${styles.section} ${styles.about}`}><div><p className={styles.eyebrow}>04 / A LITTLE ABOUT ME</p><h2>Behind every system,<br/><em>a curious mind.</em></h2><p className={styles.aboutLead}>I enjoy the work you don’t always see: the authorization boundary, the event flow, the cache key, the edge case.</p><p>My focus is Java backend engineering for multi-tenant systems. I care about understandable architecture, secure APIs and the details that make applications dependable.</p><p>I’m also building hands-on depth in CI/CD, Docker and Kubernetes, and exploring how better developer experiences help people learn.</p><div className={styles.education}><span>EDUCATION / 2025</span><strong>B.Tech · Computer Science</strong><p>Medi-Caps University, Indore</p></div></div><aside className={styles.principles}><span className={styles.bigQuote}>“</span><p>Make the complex<br/><em>feel considered.</em></p><div><span>01</span> Clear service boundaries</div><div><span>02</span> Security at every layer</div><div><span>03</span> Keep learning. Keep building.</div></aside></section>
 <section className={styles.section}><div className={styles.sectionHeading}><p className={styles.eyebrow}>05 / MY TOOLKIT</p><h2>The tools.<br/><em>The thinking.</em></h2><p>What I work with, and<br/>what I’m learning next.</p></div><div className={styles.toolkit}>{toolkit.map((group,i)=><article key={group.title}><span>0{i+1}</span><h3>{group.title}</h3><p>{group.text}</p><small>{group.detail}</small></article>)}</div><div className={styles.learning}><span className={styles.dot}/><strong>Currently learning</strong><span>CI/CD · Jenkins · GitHub Actions · Docker · Kubernetes</span></div><p className={styles.integrationNote}>Also familiar with Meta messaging integrations: WhatsApp, Instagram and Messenger; SSE and WebSocket communication.</p></section>
 <section id="contact" className={styles.contact}><p className={styles.eyebrow}>06 / START A CONVERSATION</p><h2>Something worth building?<br/><em>Let’s talk.</em></h2><p>For backend engineering conversations, collaboration,<br/>or a thoughtful idea you’d like to bring to life.</p><div className={styles.contactActions}><a className={styles.email} href={`mailto:${portfolio.email}`}>{portfolio.email}<ArrowUpRight size={24}/></a><button onClick={()=>void copyEmail()} aria-label="Copy email address" className={styles.copy}>{copied?<Check size={17}/>:<Copy size={17}/>}</button></div>{copyError&&<p role="status">{copyError}</p>}<div className={styles.contactLinks}><a href={portfolio.resumeUrl} download><Download size={15}/>Download résumé</a>{portfolio.githubUrl&&<a href={portfolio.githubUrl} target="_blank" rel="noopener noreferrer"><Github size={16}/>GitHub</a>}{portfolio.linkedinUrl&&<a href={portfolio.linkedinUrl} target="_blank" rel="noopener noreferrer"><Linkedin size={16}/>LinkedIn</a>}<a href={`mailto:${portfolio.email}`}><Mail size={16}/>Say hello</a></div></section>
 </main><footer className={styles.footer}><span className={styles.signature}>Sarthak.</span><span>Built with care. Designed to last.</span><a href="#top">Back to top ↑</a></footer>
 </div>;
}
