'use client';
import type {JourneyState} from '@/lib/journey';
import {useEffect,useState} from 'react';
import {api} from '@/lib/api/client';
export function FirstDayBrief({state,name,employeeId,preview=false}:{state:JourneyState;name:string;employeeId:string;preview?:boolean}){
 const [first,setFirst]=useState<{ticketKey:string;title:string}>();
 useEffect(()=>{let alive=true;if(!preview&&state.journey.status==='ASSIGNED')void api.getCurrentEnrollment().then(async r=>{if(!r.data)return;const w=await api.getWorkspace(r.data.id);if(alive)setFirst(w.data.tickets.find(t=>t.status==='TODO')||w.data.tickets[0]);}).catch(()=>{});return()=>{alive=false;};},[preview,state.journey.status,employeeId]);
 const selected=state.recommendations.find(r=>r.project.id===state.journey.preferredProjectId)||(!state.journey.preferredProjectId?state.recommendations[0]:undefined);
 return <section className="my-6 rounded-2xl overflow-hidden border border-indigo-300/40 bg-gradient-to-br from-slate-950 via-indigo-950 to-slate-900 p-6 text-white text-left journey-enter"><div className="flex justify-between gap-4"><span className="text-[10px] tracking-[.2em] text-indigo-300">DEVSIM / {preview?'FIRST-DAY PREVIEW':'DEVELOPER WELCOME KIT'}</span><span className="text-xs font-mono text-slate-400">DS-{employeeId.slice(0,8).toUpperCase()}</span></div><h3 className="mt-5 text-2xl font-bold">{name}</h3><p className="text-sm text-indigo-300 mt-1">Developer Trainee · {selected?.project.company?.name||'DevSim engineering team'}</p><div className="mt-5 grid sm:grid-cols-2 gap-4 text-xs"><div><p className="text-slate-400">YOUR FOUNDATION</p><p className="mt-2 leading-5">{state.journey.skills||'Skills you are starting to learn'}</p></div><div><p className="text-slate-400">YOUR DIRECTION</p><p className="mt-2 leading-5">{state.journey.goal||'Choose your career goal'} · {state.journey.weeklyHours}h/week</p></div><div><p className="text-slate-400">YOUR FIRST PROJECT</p><p className="mt-2">{selected?.project.name||'Project selection pending'}</p></div><div><p className="text-slate-400">WHAT YOU WILL PRACTICE</p><p className="mt-2 leading-5">{selected?.learningSkills.join(', ')||'Implementation, testing and code review'}</p></div></div>{first&&<p className="mt-5 rounded-xl bg-white/5 p-3 text-sm"><span className="text-indigo-300">First ticket / {first.ticketKey}</span><span className="block mt-1">{first.title}</span></p>}<p className="mt-5 pt-4 border-t border-white/10 text-xs leading-5 text-slate-300">First-day brief: start with your project instructions, pick a starter ticket and ask your Tech Lead for help. {state.journey.assessmentSkipped?'Challenge skipped; initial difficulty stays conservative.':'Your ticket reviews will guide the next sprint.'}</p></section>;
}
