'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Github,GitPullRequest,CheckCircle2,Copy,RefreshCw} from 'lucide-react';
import {githubRequest,GitHubAccount,GitHubWorkspace} from '@/lib/github';

export function GitHubIntegration({enrollmentId,onSync,onRepositoryChange}:{enrollmentId?:string;onSync?:()=>void;onRepositoryChange?:(ready:boolean)=>void}){
 const [account,setAccount]=useState<GitHubAccount>();const [workspace,setWorkspace]=useState<GitHubWorkspace>();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [copied,setCopied]=useState('');
 const syncCallback=useRef(onSync);syncCallback.current=onSync;const previousPRs=useRef<string>();
 const load=useCallback(async()=>{try{setAccount(await githubRequest<GitHubAccount>('/account'));if(enrollmentId){const next=await githubRequest<GitHubWorkspace>(`/projects/${enrollmentId}`);setWorkspace(next);onRepositoryChange?.(!!next.name);const snapshot=JSON.stringify(next.pullRequests);if(previousPRs.current!==undefined&&previousPRs.current!==snapshot)syncCallback.current?.();previousPRs.current=snapshot;}}catch(e){setError((e as Error).message);}},[enrollmentId,onRepositoryChange]);
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),30000);return()=>clearInterval(timer);},[load]);
 async function action(kind:string){setBusy(true);setError('');try{if(kind==='connect'){const r=await githubRequest<{url:string}>('/auth-url');window.location.assign(r.url);return;}if(kind==='disconnect')await githubRequest('/disconnect','DELETE');else if(enrollmentId)await githubRequest(`/projects/${enrollmentId}/${kind}`,'POST');await load();if(kind==='sync')onSync?.();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function copy(text:string){try{await navigator.clipboard.writeText(text);setCopied(text);}catch{setError('Clipboard unavailable. Select and copy the command.');}}
 return <section className="surface-card p-5 space-y-4 my-5"><div className="flex flex-wrap justify-between gap-3"><div className="flex gap-3 items-center"><Github size={24}/><div><h2 className="font-semibold">GitHub workspace</h2><p className="text-xs text-slate-500">Real repositories. Live pull requests. Reviewed work.</p></div></div>{account?.connected?<div className="flex gap-3 items-center">{account.avatar&&<img src={account.avatar} alt="GitHub avatar" className="w-8 h-8 rounded-full"/>}<span className="text-sm">Connected as @{account.username}</span><button disabled={busy} className="text-xs underline" onClick={()=>void action('disconnect')}>Disconnect</button></div>:<button disabled={busy||!account?.configured} className="rounded-lg bg-violet-600 text-white px-4 py-2 disabled:opacity-50" onClick={()=>void action('connect')}>Connect GitHub</button>}</div>
 {account&&!account.configured&&<p className="text-sm text-amber-600">GitHub OAuth requires backend configuration. See GITHUB_SETUP.md.</p>}{account?.connected&&account.botInstallUrl&&<a href={account.botInstallUrl} target="_blank" rel="noopener noreferrer" className="inline-block text-sm underline text-violet-500">Install DevSim review bot on your project repository</a>}{error&&<p role="alert" className="text-sm text-red-500">{error}</p>}
 {enrollmentId&&account?.connected&&<>{!workspace?.name?<div><p className="text-sm mb-3">Create a public project repository in your GitHub account from the configured template or a starter README.</p><button disabled={busy} onClick={()=>void action('provision-repo')} className="bg-violet-600 text-white px-4 py-2 rounded-lg">{busy?'Setting up…':'Setup GitHub Workspace'}</button></div>:<><div className="flex flex-wrap gap-4 items-center"><a href={workspace.url} target="_blank" rel="noopener noreferrer" className="text-violet-500 underline">{workspace.name}</a><button disabled={busy} onClick={()=>void action('sync')} className="flex items-center gap-2 text-sm"><RefreshCw size={15}/>{busy?'Syncing / reviewing…':'Sync PRs'}</button><button disabled={busy} onClick={()=>void action('setup')} className="text-xs underline">Repair README / webhook</button><a href="/my-portfolio" className="text-sm underline">My verified portfolio</a></div>
 <div className="rounded-lg bg-slate-100 dark:bg-slate-950 p-3 flex gap-3 items-start"><code className="text-xs break-all flex-1">git clone {workspace.url}.git</code><button aria-label="Copy clone command" onClick={()=>void copy(`git clone ${workspace.url}.git`)}><Copy size={15}/></button></div>
 <label className="block text-xs text-slate-500">Ticket branch<select className="mt-2 w-full rounded-lg bg-slate-100 dark:bg-slate-950 p-3 text-sm" defaultValue="" onChange={e=>void copy(`git checkout -b ${e.target.value}`)}><option value="" disabled>Select a ticket to copy its branch command</option>{workspace.branches.map(b=><option key={b.ticket} value={b.branch}>{b.ticket} · {b.branch}</option>)}</select></label>{copied&&<p className="text-xs text-emerald-600">Copied: {copied}</p>}
 <p className="text-xs text-slate-500">Push your ticket branch and open a PR against the default branch. {workspace.webhookConfigured?'Webhook events update DevSim automatically.':'Local webhook is not configured. Click Sync PRs after opening or updating your PR.'}</p>
 {workspace.pullRequests.length===0&&<p className="text-sm text-slate-500">Your ticket PRs will appear here.</p>}{workspace.pullRequests.map(pr=><article key={pr.pr_number} className="border border-slate-200 dark:border-slate-700 rounded-lg p-3"><a className="flex items-center gap-2 text-sm font-semibold" href={pr.url} target="_blank" rel="noopener noreferrer"><GitPullRequest size={16}/>PR #{pr.pr_number} · {pr.merged?'Merged':pr.state} {pr.approved&&<CheckCircle2 size={16} className="text-emerald-500"/>}</a><p className="text-xs text-violet-500 mt-2">AI review: {pr.review_status.replaceAll('_',' ')}</p>{pr.review_body&&<details className="text-sm mt-2"><summary>Review feedback</summary><p className="whitespace-pre-wrap mt-2">{pr.review_body.replace(/<!--.*?-->/g,'')}</p></details>}</article>)}</>}</>}
 </section>;
}
